# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
    docker:
      # specify the version you desire here
      - image: jimador/docker-jdk-8-maven-node
    working_directory: ~/SAWS
    steps:
      - checkout
      - run:
          name: Assemble JAR
          command: |
            now="$(date)"
            sudo apt-get install ant -y
            sudo apt install zip unzip
            npm install -g github-release-cli
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
               ant -f build.xml
            fi
      # As the JAR was only assembled in the first build container, build/libs will be empty in all the other build containers.
      - store_artifacts:
          path: build/libs
  
workflows:
  version: 2
  build:
    jobs:
      - build